### ISSUE TITLE
Il manque le .idea

### ISSUE THREAD

**Issue by lbassin** [AxelE/RubyPokedex#1]
Tu as oublié de commit le .idea

**Comment by lbassin** [comment]
Faut lancer wamp non ?

**Comment by Mapsred** [comment]
mkdir .idea
touch .idea/.gitkeep
git commit -am "Add missing .idea folder"

**Comment by x-Raz** [comment]
coucou

**Comment by lbassin** [comment]
![coucou](https://user-images.githubusercontent.com/11029822/40351178-0f72e66c-5dac-11e8-8d12-da0ae4c7d89e.gif)

**Comment by x-Raz** [comment]
![unknown](https://user-images.githubusercontent.com/12535829/40351186-1850b16a-5dac-11e8-9d63-7d1ca5249023.png)
