### ISSUE TITLE
Je suis à la recherche de votre .idea

### ISSUE THREAD

**Issue by x-Raz** [AxelE/RubyPokedex#6]
Guttentag

**Comment by AxelE** [comment]
Wunderbar

**Comment by x-Raz** [comment]
C'est pas résolu

**Comment by AxelE** [comment]
T'es sur ?

**Comment by x-Raz** [comment]
![unknown](https://user-images.githubusercontent.com/12535829/40351558-008fb0fc-5dad-11e8-98bf-04740dd7ab01.png)
